// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SuperMarket.Lib.DA.EFCore;

namespace SuperMarket.Web.Migrations
{
    [DbContext(typeof(SuperMarketContext))]
    [Migration("20190718212712_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SuperMarket.Lib.Core.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Discriminator")
                        .IsRequired();

                    b.Property<string>("Email");

                    b.Property<string>("Name");

                    b.Property<string>("Password");

                    b.Property<string>("Surname1");

                    b.Property<string>("Surname2");

                    b.Property<string>("Token");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasDiscriminator<string>("Discriminator").HasValue("User");
                });

            modelBuilder.Entity("SuperMarket.Lib.Models.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid?>("ClientsId");

                    b.Property<Guid?>("EmployeesId");

                    b.HasKey("Id");

                    b.HasIndex("ClientsId");

                    b.HasIndex("EmployeesId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("SuperMarket.Lib.Models.OrderItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid?>("OrdersId");

                    b.Property<Guid?>("ProductsId");

                    b.Property<int>("Quantity");

                    b.HasKey("Id");

                    b.HasIndex("OrdersId");

                    b.HasIndex("ProductsId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("SuperMarket.Lib.Models.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Price");

                    b.Property<string>("ProductName");

                    b.HasKey("Id");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("SuperMarket.Lib.Models.Client", b =>
                {
                    b.HasBaseType("SuperMarket.Lib.Core.User");

                    b.HasDiscriminator().HasValue("Client");
                });

            modelBuilder.Entity("SuperMarket.Lib.Models.Employee", b =>
                {
                    b.HasBaseType("SuperMarket.Lib.Core.User");

                    b.HasDiscriminator().HasValue("Employee");
                });

            modelBuilder.Entity("SuperMarket.Lib.Models.Order", b =>
                {
                    b.HasOne("SuperMarket.Lib.Models.Client", "Clients")
                        .WithMany("Orders")
                        .HasForeignKey("ClientsId");

                    b.HasOne("SuperMarket.Lib.Models.Employee", "Employees")
                        .WithMany("Orders")
                        .HasForeignKey("EmployeesId");
                });

            modelBuilder.Entity("SuperMarket.Lib.Models.OrderItem", b =>
                {
                    b.HasOne("SuperMarket.Lib.Models.Order", "Orders")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrdersId");

                    b.HasOne("SuperMarket.Lib.Models.Product", "Products")
                        .WithMany("OrderItems")
                        .HasForeignKey("ProductsId");
                });
#pragma warning restore 612, 618
        }
    }
}
